const dbInit = [
  'CREATE TABLE IF NOT EXISTS Grades (Identifier TEXT PRIMARY KEY, Title TEXT NOT NULL, Grade REAL, Credits_All INTEGER NOT NULL, Credits_Charged INTEGER, Status TEXT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS Events (EventID TEXT PRIMARY KEY, Title TEXT NOT NULL, Abbreviation TEXT, Start TEXT, End TEXT, Room TEXT, WeekFrom TEXT NOT NULL, Weekday TEXT NOT NULL, HIDE_FLAG INTEGER NOT NULL DEFAULT 0, MODE INTEGER NOT NULL DEFAULT 0)',
];

const dbMigrate = [
  'ALTER TABLE Events ADD COLUMN HIDE_FLAG INTEGER NOT NULL DEFAULT 0',
  'ALTER TABLE Events ADD COLUMN MODE INTEGER NOT NULL DEFAULT 0',
];
